# Generated by Django 3.0.2 on 2020-01-09 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
        migrations.CreateModel(
            name='Costs',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('amount', models.DecimalField(db_column='Amount', decimal_places=2, max_digits=10)),
                ('cost_type_id', models.IntegerField(db_column='Cost_Type_ID')),
                ('project_id', models.IntegerField(db_column='Project_ID')),
            ],
            options={
                'db_table': 'costs',
            },
        ),
        migrations.CreateModel(
            name='CostTypes',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('name', models.CharField(db_column='Name', max_length=100)),
                ('parent_cost_type_id', models.IntegerField(db_column='Parent_Cost_Type_ID', null=True)),
            ],
            options={
                'db_table': 'cost_types',
            },
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.AutoField(db_column='ID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=100)),
                ('client_id', models.IntegerField(db_column='Client_ID')),
            ],
            options={
                'db_table': 'projects',
            },
        ),
    ]
